image: ubuntu:latest
pipelines:
    branches:
        master:
            - step:
                name: setup terraform, run init and plan phases, and scan with accurics
                script:
                    - export DEBIAN_FRONTEND=noninteractive
                    - apt-get update && apt-get install -y gnupg2 software-properties-common lsb-release curl wget git
                    - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
                    - apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                    - apt-get install -y terraform=1.0.3
                    - terraform init
                    - terraform validate
                    - terraform plan
                    ## run accurics cli in enforce mode
                    - wget https://downloads.accurics.com/cli/latest/accurics_linux -O accurics
                    - chmod +x accurics
                    - ./accurics init
                    #- ./accurics plan -mode=pipeline -appurl=https://e6a9-124-123-190-221.ngrok.io/ -token=6e39233d-6919-4942-9fcf-001e1036aa53 -environment=47735848-3871-4650-9b1c-220a6017e2e4
                    - ./accurics plan -mode=pipeline -appurl=https://beta.accurics.com -token=$TOKEN -env=9665e0b5-748a-4fe9-add5-c05bb114e31d
